### ISSUE TITLE
How to operate a Kadena node (KDA)

### ISSUE THREAD

**Issue by k1trusk** [kadena-community/node-setup#2]
The guide for operating KDA node is not working anymore, will be nice to have an update on one that is working. This way we can stabilize the network and be decentralized.

**Comment by ghost** [comment]
"Not working" isn't a really helpful description of the problem.
I guess your problem is because you didn't have a Domain Name so I added a script to install without one. Please post a better description of the problem and the end of the install log located at `/tmp/install.log` if possible.
